services:
  localdb:
    image: postgres:11.2  # you can pick the most recent version available
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=vbersano
      - POSTGRES_PASSWORD=pharao123
      - POSTGRES_DB=vbersano

  testdb:
    image: postgres:11.2
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=vbersano
      - POSTGRES_PASSWORD=pharao123
      - POSTGRES_DB=vbersano_testdb